---
- name: Install jenkins.
  hosts: jenkins
  remote_user: centos
  pre_tasks:
    - name: Wait for server ssh
      wait_for:
        port: 22
        delay: 5
        host: "{{ ansible_ssh_host }}"
      delegate_to: localhost
      register: ssh_wait_check
      until: ssh_wait_check|success
      retries: 3

  pre_tasks:
    - name: Install Jenkins repo.
      copy:
        src: files/jenkins/etc/yum.repos.d/jenkins.repo
        dest: /etc/yum.repos.d
      sudo: yes

    - name: Import GPG key for Jenkins repo.
      rpm_key:
        key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
      sudo: yes

  roles:
    - ansible-role-jenkins
    - ansible-role-nginx
    - ansible-role-ssh
    - ansible-role-jenkins-groovy
    - ansible-role-jenkins-jobs

  post_tasks:
    - name: copy jenkins configuration.
      copy:
        dest: /var/lib/jenkins
        group: jenkins
        mode: 0444
        owner: jenkins
        src: files/jenkins/var/lib/jenkins/{{ item }}
      with_items:
        - hudson.plugins.gearman.GearmanPluginConfig.xml
        - org.jenkinsci.main.modules.sshd.SSHD.xml
        - org.jenkinsci.plugins.ZMQEventPublisher.HudsonNotificationProperty.xml
      notify: Restart jenkins
      sudo: yes

  vars_files:
    - vars/jenkins.yaml
