---
- name: Install nodepool.
  hosts: nodepool
  remote_user: centos
  pre_tasks:
    - name: Wait for server ssh
      wait_for:
        port: 22
        delay: 5
        host: "{{ ansible_ssh_host }}"
      delegate_to: localhost
      register: ssh_wait_check
      until: ssh_wait_check|success
      retries: 3

  roles:
    - ansible-role-diskimage-builder
    - ansible-role-nodepool
  vars_files:
    - vars/nodepool.yaml
