---
- name: Install nodepool.
  hosts: nodepool
  remote_user: centos
  pre_tasks:
    - name: Wait for server ssh
      wait_for:
        port: 22
        delay: 5
        host: "{{ ansible_ssh_host }}"
      delegate_to: localhost
      register: ssh_wait_check
      until: ssh_wait_check|success
      retries: 3

      # https://bugzilla.redhat.com/show_bug.cgi?id=1289073
    - name: Enable CR repository for libunwind
      yum:
        enablerepo: cr
        name: libunwind
      sudo: yes

  roles:
    - ansible-role-diskimage-builder
    - ansible-role-nodepool
    - ansible-role-ssh
    - ansible-role-nginx
  vars_files:
    - vars/nodepool.yaml
