---
- name: Install nodepool.
  hosts: nodepool
  remote_user: centos

  roles:
    - ansible-role-sudoers
    - ansible-role-diskimage-builder
    - ansible-role-nodepool
    - ansible-role-ssh
    - ansible-role-nginx
    - ansible-role-logrotate
  vars_files:
    - vars/nodepool.yaml
