# ansible-role-diskimage-builder
- src: https://github.com/pabelanger/ansible-role-diskimage-builder

# ansible-role-ngnix
- src: https://github.com/pabelanger/ansible-role-ngnix

# ansible-role-nodepool
- src: https://github.com/openstack/ansible-role-nodepool

# ansible-role-zuul
- src: https://github.com/pabelanger/ansible-role-zuul
