---
- name: Install zuul.
  hosts: zuul
  remote_user: centos

  roles:
    - ansible-role-zuul
    - ansible-role-ssh
    - ansible-role-logrotate

  vars_files:
    - "{{ config_git_dest }}/vars/zuul.yaml"
