---
- name: Install zuul.
  hosts: zuul
  remote_user: centos
  pre_tasks:
    - name: Wait for server ssh
      wait_for:
        port: 22
        delay: 5
        host: "{{ ansible_ssh_host }}"
      delegate_to: localhost
      register: ssh_wait_check
      until: ssh_wait_check|success
      retries: 3

  roles:
    - ansible-role-zuul
    - ansible-role-ssh
  vars_files:
    - vars/zuul.yaml
